BTC_PROTOCOL: "http"
BTC_PORT: 18332
ZMQ_PORT: 49332
BTC_HOST: "127.0.0.1"
BTC_RPC_USERNAME: "user"
BTC_RPC_PASSWORD: "password"
BTC_NETWORK: "testnet4"

NOSTR_RELAYS: ["wss://lightningrelay.com", "wss://relay.damus.io", "wss://nostr.einundzwanzig.space", "wss://relay01.lnfi.network/", "wss://njump.me/", "wss://fiatjaf.com/"]

WATCHTOWERS:
  LEGACY_SWAPS: true
  SPV_SWAPS: true
  HTLC_SWAPS: true

CLI_ADDRESS: "127.0.0.1"
CLI_PORT: 40220

STARKNET:
  MNEMONIC_FILE: "mnemonic.txt"
  RPC_URL: ""
  #WebSocket URL can be additionally configured as well
  #WS_URL: ""
  CHAIN: "SEPOLIA"

  MAX_L1_FEE_GWEI: 20000000
  MAX_L2_FEE_GWEI: 4000000
  MAX_L1_DATA_FEE_GWEI: 10000000

CITREA:
  MNEMONIC_FILE: "mnemonic.txt"
  #RPC URL, can either be an http or ws RPC
  RPC_URL: "https://rpc.testnet.citrea.xyz"
  MAX_LOGS_BLOCK_RANGE: 900
  CHAIN: "TESTNET4"

  MAX_FEE_GWEI: 2
  FEE_TIP_GWEI: 0.001
