BTC_PROTOCOL: "http"
BTC_PORT: 18332
ZMQ_PORT: 49332
BTC_HOST: "127.0.0.1"
BTC_RPC_USERNAME: "user"
BTC_RPC_PASSWORD: "password"
BTC_NETWORK: "regtest"

NOSTR_RELAYS: ["wss://lightningrelay.com", "wss://relay.damus.io", "wss://nostr.einundzwanzig.space", "wss://relay01.lnfi.network/", "wss://njump.me/", "wss://fiatjaf.com/"]

WATCHTOWERS:
  LEGACY_SWAPS: true
  SPV_SWAPS: true
  HTLC_SWAPS: true

CLI_ADDRESS: "127.0.0.1"
CLI_PORT: 40220

SOLANA:
  MNEMONIC_FILE: "mnemonic.txt"
  RPC_URL: "http://127.0.0.1:8899"

  MAX_FEE_MICRO_LAMPORTS: 250000
  STATIC_TIP: 10000

STARKNET:
  MNEMONIC_FILE: "mnemonic.txt"
  RPC_URL: "http://127.0.0.1:5050/rpc/v0_8"
  #WebSocket URL can be additionally configured as well
  #WS_URL: ""
  CHAIN: "SEPOLIA"

  MAX_L1_FEE_GWEI: 20000000
  MAX_L2_FEE_GWEI: 4000000
  MAX_L1_DATA_FEE_GWEI: 10000000
