BTC_PROTOCOL: "http"
BTC_PORT: 8332
ZMQ_PORT: 39332
BTC_HOST: "127.0.0.1"
BTC_RPC_USERNAME: "user"
BTC_RPC_PASSWORD: "password"
BTC_NETWORK: "mainnet"

NOSTR_RELAYS: ["wss://lightningrelay.com", "wss://relay.damus.io", "wss://nostr.einundzwanzig.space", "wss://relay01.lnfi.network/", "wss://njump.me/", "wss://fiatjaf.com/"]

WATCHTOWERS:
  LEGACY_SWAPS: true
  SPV_SWAPS: true
  HTLC_SWAPS: true

CLI_ADDRESS: "127.0.0.1"
CLI_PORT: 40220

SOLANA:
  MNEMONIC_FILE: "mnemonic.txt"
  RPC_URL: "https://api.mainnet-beta.solana.com"

  MAX_FEE_MICRO_LAMPORTS: 250000
  STATIC_TIP: 50000
#  JITO:
#    PUBKEY: "DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL"
#    ENDPOINT: "https://frankfurt.mainnet.block-engine.jito.wtf/api/v1/transactions"

STARKNET:
  MNEMONIC_FILE: "mnemonic.txt"
  RPC_URL: "https://starknet.api.onfinality.io/public/rpc/v0_9"
  #WebSocket URL can be additionally configured as well
  #WS_URL: ""
  CHAIN: "MAINNET"

  MAX_L1_FEE_GWEI: 20000000
  MAX_L2_FEE_GWEI: 4000000
  MAX_L1_DATA_FEE_GWEI: 10000000

BOTANIX:
  MNEMONIC_FILE: "mnemonic.txt"
  #RPC URL, can either be an http or ws RPC
  RPC_URL: "wss://rpc.botanixlabs.com/ws"
  MAX_LOGS_BLOCK_RANGE: 900
  CHAIN: "MAINNET"

  MAX_FEE_GWEI: 2
  FEE_TIP_GWEI: 0.001
